### ISSUE TITLE
Openshift 4.1 feature gates

### ISSUE THREAD

**Issue by pure-yesmat** [openshift/csi-driver-registrar#13]
Hello,

The documentation is not clear for openshift 4.1, do we need to enable the CSIDriverRegistry feature gate or is this enabled by default?

Also would using the vanilla kubernetes [node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar) work or do we need to use this side car?

Thanks
Youssef

**Comment by jsafrane** [comment]
CSI is not GA in 4.1 and CSIDriverRegistry is disabled there. It's going to be enabled and fully supported in 4.2.

As for sidecar images, you can use anything that supports Kubernetes 1.13 interfaces (in OCP 4.1; 1.14 in 4.2 respectively). Vanilla versions maintained by Kubernetes community are perfectly OK.

Red Hat supports CSI sidecars shipped in OCP only when used by CSI driver supported by Red Hat. However, as the source code and OKD image are public, you can use them for any other purposes, only with a community support here.

**Comment by pure-yesmat** [comment]
Thanks @jsafrane
